apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: astronomy-shop
  namespace: argocd-system
spec:
  project: default
  source:
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    chart: opentelemetry-demo
    targetRevision: 0.26.0
  destination:
    server: https://kubernetes.default.svc
    namespace: astronomy-shop
  syncPolicy:
    automated: { prune: true, selfHeal: true }